services:
  enigmatry.angularassignment.api:
    image: ${DOCKER_REGISTRY-}enigmatryangularassignmentapi
    build:
      context: .
      dockerfile: Enigmatry.AngularAssignment/Dockerfile
    ports:
      - "5000:5000"
      - "7258:7258"